"use client";
import {useEffect,useState} from 'react';
import {Mail,Plus,Eye,Send,Users,FileText,CheckCircle2,RefreshCw,ArrowLeft} from 'lucide-react';
import {authFetch} from '@/lib/auth-fetch';
import {audiences,type Campaign,type CampaignDraft} from '@/lib/lms/campaign';
import type {Course} from '@/lib/lms/types';
const blank:CampaignDraft={name:'',subject:'',body:'Hi {{first_name}},\n\n',button_text:'Explore courses',button_url:'https://pacificwavedigital.com/training-center',audience:'no_enrolment',course_id:''};
const templates=[{label:'Welcome & next steps',subject:'Your next step with Pacific Wave Digital',body:'Hi {{first_name}},\n\nWelcome to the Pacific Wave Digital Training Centre. Ready to turn your ideas into practical skills? Explore our courses in business, AI, websites, ecommerce and software development.\n\nChoose your course and complete registration to begin. If you need help choosing, reply to this email and we will guide you.',audience:'no_enrolment'}, {label:'Payment follow-up',subject:'Let us help you complete your course registration',body:'Hi {{first_name}},\n\nWe are following up on your course registration. You can check your payment status and complete any outstanding steps from your student dashboard.\n\nIf you have already uploaded your bank payment proof, thank you. Please allow our team to review it. Reply here if you need assistance.',audience:'unpaid'},{label:'Class update',subject:'An update for your training',body:'Hi {{first_name}},\n\nHere is the latest update for your course:\n\n[Add your class details and any action students need to take.]\n\nVisit your dashboard for lessons, recordings and your course community. Reply to this email if you need help.',audience:'paid'}] as const;
type Detail={campaign:Campaign;recipients:{id:string;name:string;email:string;state:string;error:string|null}[];counts:Record<string,number>;preview:string};
async function api(body?:unknown,id?:string){const r=await authFetch('/api/lms-campaigns'+(id?'?id='+id:''),body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});const d=await r.json();if(!r.ok)throw Error(d.error||'Unable to complete this action');return d;}
export default function EmailCampaigns({courses}:{courses:Course[]}){
 const [list,setList]=useState<Campaign[]>([]),[detail,setDetail]=useState<Detail|null>(null),[draft,setDraft]=useState<CampaignDraft|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[review,setReview]=useState(false),[sandbox,setSandbox]=useState(true);
 const load=async()=>{const d=await api();setList(d.campaigns);setSandbox(d.sandbox);};
 useEffect(()=>{load().catch(e=>setError(e.message));},[]);
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');setNotice('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'Please try again');}finally{setBusy(false);}};
 const open=async(id:string)=>{setDetail(await api(undefined,id));setDraft(null);setReview(false);};
 const total=Object.values(detail?.counts||{}).reduce((a,b)=>a+b,0);
 const edit=(patch:Partial<CampaignDraft>)=>setDraft(d=>d?{...d,...patch}:d);
 return <section className="ec-workspace">
  <header className="ec-header"><div><span className="lms-eyebrow">STUDENT COMMUNICATIONS</span><h2>Email campaigns</h2><p>Keep your students informed, supported and ready for their next step.</p></div><button className="lms-button" disabled={busy} onClick={()=>{setDraft({...blank});setDetail(null);setError('');setNotice('');}}><Plus size={17}/>New campaign</button></header>
  {sandbox&&<p className="lms-notice">Preview environment: tests and campaigns go to the sandbox inbox.</p>}
  {error&&<p className="lms-alert" role="alert">{error}</p>}{notice&&<p className="lms-notice" role="status">{notice}</p>}
  <div className="ec-summary"><div><FileText/><strong>{list.filter(c=>c.status==='draft').length}</strong><span>Draft campaigns</span></div><div><Send/><strong>{list.filter(c=>c.status==='sending').length}</strong><span>Sending</span></div><div><CheckCircle2/><strong>{list.filter(c=>c.status==='completed').length}</strong><span>Processed campaigns</span></div></div>
  {draft?<div className="ec-editor"><form className="lms-panel" onSubmit={e=>{e.preventDefault();run(async()=>{const d=await api({action:'save',draft});await load();await open(d.campaign.id);setNotice('Draft saved. Review your audience and email before sending.');});}}>
   <h3>{draft.id?'Edit draft':'Create your message'}</h3><label>Start with a template<select defaultValue="" onChange={e=>{const t=templates[Number(e.target.value)];if(t)edit({subject:t.subject,body:t.body,audience:t.audience,name:t.label});}}><option value="" disabled>Choose a starting point</option>{templates.map((t,i)=><option key={t.label} value={i}>{t.label}</option>)}</select></label>
   <label>Campaign name<input required maxLength={120} value={draft.name} onChange={e=>edit({name:e.target.value})} placeholder="October enrolment follow-up"/></label>
   <label>Subject line<input required maxLength={180} value={draft.subject} onChange={e=>edit({subject:e.target.value})}/></label>
   <label>Message<textarea required minLength={10} maxLength={15000} rows={12} value={draft.body} onChange={e=>edit({body:e.target.value})}/></label><p className="lms-muted">Use {'{{first_name}}'} for a personal greeting. Separate paragraphs with a blank line. Your message is wrapped in Pacific Wave Digital branding.</p>
   <div className="ec-two"><label>Button text<input required maxLength={60} value={draft.button_text} onChange={e=>edit({button_text:e.target.value})}/></label><label>Button destination<input required type="url" value={draft.button_url} onChange={e=>edit({button_url:e.target.value})}/></label></div>
   <button className="lms-button" disabled={busy}><FileText size={17}/>Save draft</button><button type="button" className="lms-text" disabled={busy} onClick={()=>setDraft(null)}>Cancel editing</button>
  </form><aside className="lms-panel"><Users size={28}/><h3>Choose your audience</h3><label>Who should receive this?<select value={draft.audience} onChange={e=>edit({audience:e.target.value as CampaignDraft['audience'],course_id:''})}>{Object.entries(audiences).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>
   {['paid','unpaid','not_in_course'].includes(draft.audience)&&<label>Course<select value={draft.course_id} onChange={e=>edit({course_id:e.target.value})}><option value="">{draft.audience==='not_in_course'?'Choose a course':'All courses'}</option>{courses.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label>}
   <p>Student audiences include verified accounts associated with this training centre. Duplicate email addresses and unsubscribed contacts are excluded.</p><p>Recipients are fixed when you review the audience. You can review again to include newer registrations.</p><p>Replies go to <strong>steve@pacificwavedigital.com</strong>.</p>
  </aside></div>:detail?<div>
   <div className="ec-toolbar"><button className="lms-text" onClick={()=>{setDetail(null);setReview(false);}}><ArrowLeft size={16}/> All campaigns</button><span className="lms-pill">{detail.campaign.status}</span><button className="lms-text" disabled={busy} onClick={()=>run(()=>open(detail.campaign.id))}><RefreshCw size={16}/>Refresh</button></div>
   <div className="ec-editor"><div className="lms-panel"><h3>{detail.campaign.name}</h3><p><strong>Subject:</strong> {detail.campaign.subject}</p><p>{audiences[detail.campaign.audience]}{detail.campaign.course_id?' · '+courses.find(c=>c.id===detail.campaign.course_id)?.title:''}</p>
    <iframe title="Email preview" sandbox="" srcDoc={detail.preview} className="ec-preview"/>
   </div><aside className="lms-panel"><h3>Campaign controls</h3><div className="ec-recipient-total"><Users/><strong>{total}</strong><span>{detail.campaign.prepared?'Recipients in this audience':'Review to count recipients'}</span></div>
    {detail.campaign.status==='draft'&&<>
     <button className="lms-button" disabled={busy} onClick={()=>run(async()=>{await api({action:'prepare',id:detail.campaign.id,revision:detail.campaign.revision});await open(detail.campaign.id);setReview(true);})}><Eye size={17}/>Review audience</button>
     <button className="lms-text" disabled={busy} onClick={()=>setDraft({...detail.campaign,course_id:detail.campaign.course_id||''})}>Edit message or audience</button>
     {review&&total>0&&<div className="ec-confirm"><h4>Ready to send?</h4><p>This sends “{detail.campaign.subject}” to {total} {sandbox?'sandbox test deliveries':'recipients'}. Each person receives a separate email.</p><button className="lms-button" disabled={busy} onClick={()=>run(async()=>{await api({action:'send',id:detail.campaign.id,revision:detail.campaign.revision});await load();await open(detail.campaign.id);setNotice('Campaign queued. Sending continues in the background. Refresh to see progress.');})}><Send size={16}/>Send to {total} recipients</button></div>}
    </>}
    <button className="lms-text" disabled={busy} onClick={()=>run(async()=>{const d=await api({action:'test',id:detail.campaign.id});setNotice(d.message);})}>Send test to my admin email</button>
    {detail.campaign.status!=='draft'&&<><button className="lms-text" disabled={busy} onClick={()=>run(async()=>{const d=await api({action:'refresh',id:detail.campaign.id});await open(detail.campaign.id);setNotice(d.message);})}>Check delivery with provider</button><dl className="ec-counts">{Object.entries(detail.counts).filter(([,n])=>n>0).map(([s,n])=><div key={s}><dt>{s.replaceAll('_',' ')}</dt><dd>{n}</dd></div>)}</dl></>}
    <p className="lms-muted">Accepted means the email provider accepted the message; it does not confirm inbox delivery. Use Check delivery for provider updates.</p>
    {detail.campaign.status==='sending'&&<button className="lms-text" disabled={busy} onClick={()=>run(async()=>{const d=await api({action:'cancel',id:detail.campaign.id});await load();await open(detail.campaign.id);setNotice(d.message);})}>Cancel remaining deliveries</button>}
    <button className="lms-text" onClick={()=>{const {id,revision,...copy}=detail.campaign;void id;void revision;setDraft({...copy,name:copy.name+' (copy)',course_id:copy.course_id||''});}}>Copy as a new draft</button>
   </aside></div>
   <div className="lms-panel ec-table"><h3>Recipients & delivery</h3><p>Showing up to 500 recipients. Totals above include the full audience.</p><table><thead><tr><th>Student</th><th>Email</th><th>Status</th></tr></thead><tbody>{detail.recipients.map(r=><tr key={r.id}><td>{r.name}</td><td>{r.email}</td><td>{r.state.replaceAll('_',' ')}{r.error&&<small>{r.error}</small>}</td></tr>)}</tbody></table>{!detail.recipients.length&&<p>No recipients yet. Review the audience to populate this list.</p>}</div>
  </div>:<div className="lms-panel"><h3>Your campaigns</h3><p>Draft, review and send correspondence from one place.</p>{!list.length?<div className="ec-empty"><Mail size={40}/><h3>Your first campaign starts here</h3><p>Welcome new students, follow up on enrolments or share an important class update.</p></div>:list.map(c=><button key={c.id} className="ec-campaign-row" disabled={busy} onClick={()=>run(()=>open(c.id))}><Mail size={22}/><span><strong>{c.name}</strong><small>{c.subject}</small></span><span className="lms-pill">{c.status}</span></button>)}</div>}
 </section>;
}
