import test from 'node:test';import assert from 'node:assert/strict';import {PGlite} from '@electric-sql/pglite';import {readFile} from 'node:fs/promises';import {campaignSchema,campaignContent} from '../src/lib/lms/campaign';
const draft={name:'Test campaign',subject:'Welcome',body:'Hi {{first_name}},\n\n<script>unsafe</script>',button_text:'View courses',button_url:'https://example.com',audience:'all',course_id:''};
test('campaign messages escape HTML and validate destinations and audiences',()=>{const c=campaignSchema.parse(draft);assert.ok(campaignContent(c,'Malia').html.includes('Hi Malia'));assert.ok(!campaignContent(c).html.includes('<script>'));assert.equal(campaignSchema.safeParse({...draft,button_url:'javascript:alert(1)'}).success,false);assert.equal(campaignSchema.safeParse({...draft,audience:'not_in_course'}).success,false);});
test('campaign SQL isolates training audience, snapshots recipients and restricts access',async()=>{
 const db=new PGlite();try{await db.exec(`CREATE ROLE anon;CREATE ROLE authenticated;CREATE ROLE service_role;CREATE SCHEMA auth;CREATE TABLE auth.users(id uuid PRIMARY KEY,email text,email_confirmed_at timestamptz);CREATE TABLE pwd_lms_profiles(user_id uuid,full_name text);CREATE TABLE pwd_lms_orders(user_id uuid,name text,email text,created_at timestamptz,course_id uuid,status text);CREATE TABLE pwd_lms_account_emails(email text);CREATE TABLE pwd_lms_courses(id uuid PRIMARY KEY);CREATE TABLE pwd_training_registrations(email text,full_name text,future_training_opt_in boolean);`);
 const sql=await readFile('supabase/migrations/20260916_training_campaigns.sql','utf8');await db.exec(sql);await db.exec(sql);await db.exec(await readFile("supabase/migrations/20260918_lms_access_campaigns.sql","utf8"));
 await db.exec(`INSERT INTO auth.users VALUES('00000000-0000-0000-0000-000000000001','student@example.com',now()),('00000000-0000-0000-0000-000000000002','other-app@example.com',now());INSERT INTO pwd_lms_profiles VALUES('00000000-0000-0000-0000-000000000001','Student');`);
 assert.equal((await db.query("SELECT * FROM pwd_campaign_audience('all',null)")).rows.length,1);
 await db.exec("INSERT INTO pwd_lms_orders(user_id,email,name,status) VALUES('00000000-0000-0000-0000-000000000001','student@example.com','Student','granted')");assert.equal((await db.query("SELECT * FROM pwd_campaign_audience('paid',null)")).rows.length,1);assert.equal((await db.query("SELECT * FROM pwd_campaign_audience('unpaid',null)")).rows.length,0);
 const r=await db.query<{id:string;revision:string}>("SELECT * FROM pwd_save_campaign($1::jsonb,null,true)",[JSON.stringify(draft)]);const c=r.rows[0];
 assert.equal((await db.query<{pwd_prepare_campaign:number}>('SELECT pwd_prepare_campaign($1,$2)',[c.id,c.revision])).rows[0].pwd_prepare_campaign,1);
 await assert.rejects(()=>db.query('SELECT pwd_prepare_campaign($1,$2)',[c.id,crypto.randomUUID()]));
 await db.query("UPDATE pwd_lms_campaigns SET status='sending' WHERE id=$1",[c.id]);assert.equal((await db.query('SELECT * FROM pwd_claim_campaign_recipient(false)')).rows.length,0);assert.equal((await db.query('SELECT * FROM pwd_claim_campaign_recipient(true)')).rows.length,1);assert.equal((await db.query('SELECT * FROM pwd_claim_campaign_recipient(true)')).rows.length,0);
 await db.exec("INSERT INTO pwd_lms_email_suppressions(email,reason) VALUES('student@example.com','unsubscribed')");assert.equal((await db.query("SELECT * FROM pwd_campaign_audience('all',null)")).rows.length,0);
 await db.exec('SET ROLE authenticated');await assert.rejects(()=>db.query('SELECT * FROM pwd_lms_campaigns'));await assert.rejects(()=>db.query("SELECT * FROM pwd_campaign_audience('all',null)"));
 }finally{await db.close();}
});
