'use client';
import {useCallback,useEffect,useState} from 'react';
import {Trophy,Gift,Target,Clock3,CheckCircle2} from 'lucide-react';
import {authFetch} from '@/lib/auth-fetch';
import {challengeDate,challengePhase,participationCriteria,participationRules,participationTotal,type Challenge,type Claim} from '@/lib/lms/challenges';
import styles from './challenges.module.css';
export async function challengeRequest(path:string,body?:unknown){const r=await authFetch('/api/lms-challenges'+path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:undefined);const data=await r.json();if(!r.ok)throw Error(data.error||'Could not load challenges.');return data;}
export default function Challenges({courseId}:{courseId:string}){
 const [data,setData]=useState<{challenges:Challenge[];claims:Claim[]}|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState(''),[message,setMessage]=useState('');
 const load=useCallback(async()=>{setData(await challengeRequest('?course='+courseId));},[courseId]);
 useEffect(()=>{let current=true;challengeRequest('?course='+courseId).then(d=>{if(current)setData(d);}).catch(e=>{if(current)setError(e.message);});return()=>{current=false;};},[courseId]);
 async function submit(e:React.FormEvent<HTMLFormElement>,c:Challenge){e.preventDefault();const form=new FormData(e.currentTarget);setBusy(true);setError('');try{await challengeRequest('',{action:'submit',claim:{challenge_id:c.id,evidence:form.get('evidence'),evidence_url:form.get('url'),achieved_at:c.selection_mode==='participation'?new Date().toISOString():new Date(String(form.get('achieved'))+'+11:00').toISOString()}});setSelected('');setMessage('Proof submitted privately. Your trainer will review it.');await load();}catch(e){setError(e instanceof Error?e.message:'Please try again.');}finally{setBusy(false);}}
 const participationWinner=data?.claims.some(r=>['winner','delivered'].includes(r.status)&&data.challenges.some(c=>c.id===r.challenge_id&&c.selection_mode==='participation'));
 return <section className={styles.root} aria-label="Course challenges">
 <header className={styles.hero}><span className={styles.eyebrow}><Trophy size={17}/> PWD CHALLENGES</span><h2>Small steps.<br/>Real achievements.</h2><p>Put your learning into action. Share your progress, prove your milestone, and work towards a reward.</p><div className={styles.heroTags}><span><Target size={16}/> Build something real</span><span><Gift size={16}/> Earn a little extra</span></div></header>
 <div className={styles.steps}><span><b>01</b> Choose a challenge</span><span><b>02</b> Submit private proof</span><span><b>03</b> Trainer verifies results</span></div>
 {error&&<p role="alert" className={styles.error}>{error} <button onClick={()=>{setError('');load().catch(e=>setError(e.message));}}>Retry</button></p>}{message&&<p role="status">{message}</p>}
 {!data&&!error&&<p role="status">Loading challenges…</p>}
 {data?.challenges.length===0&&<div className={styles.empty}><Gift size={32}/><h3>Your next challenge is on its way</h3><p>Your trainer is preparing the milestones and prizes. Check back here for the first challenge.</p></div>}
 <div className={styles.cards}>{data?.challenges.map(c=>{const claim=data.claims.find(s=>s.challenge_id===c.id),phase=challengePhase(c),participation=c.selection_mode==='participation';return <article key={c.id} className={styles.card}>
 <div className={styles.cardTop}><span className={styles.badge}>{phase}</span><span>{c.max_winners} prize {c.max_winners===1?'place':'places'}</span></div><h3>{c.title}</h3><p>{c.description}</p><div className={styles.prize}><Gift size={22}/><div><small>THE REWARD</small><strong>{c.prize}</strong></div></div>
 <p className={styles.dates}><Clock3 size={16}/><span>{challengeDate(c.opens_at)} – {challengeDate(c.closes_at)}<small>Vanuatu time · UTC+11</small></span></p>
 {participation&&<div className={styles.rubric}><strong>How your champion is chosen · 20 points</strong><ul>{participationCriteria.map(r=><li key={r.label}>{r.label} <b>5 points</b></li>)}</ul><p>{participationRules}</p><details><summary>See the scoring guide</summary>{participationCriteria.map(r=><p key={r.label}><strong>{r.label}: </strong>{r.description}</p>)}</details></div>}
 <details><summary>How to qualify & claim</summary><p>{c.proof_instructions}</p><p>Only approved students in this course can enter. Submit before closing. {participation?participationRules:"Winners are selected after closing by the earliest verified achievement time; ties use submission time. All pending entries are reviewed first."} One entry per student per challenge. No guaranteed income.</p><p>Proof is private to you and authorised staff. Prizes are arranged manually by PWD after verification; they are not automatically added to your Digi Assist account.</p></details>
 {claim?<div className={styles.status}><CheckCircle2 size={18}/><div><strong>{({pending:'Proof under review',verified:'Verified — awaiting final results',rejected:'Entry not accepted',winner:'You won — reward being arranged',delivered:'Reward delivered'})[claim.status]}</strong>{claim.review_note&&<p>{claim.review_note}</p>}{claim.scores&&<div className={styles.rubric}><strong>Your verified score: {participationTotal(claim.scores)} / 20</strong><ul>{participationCriteria.map((r,i)=><li key={r.label}>{r.label}: {claim.scores![i]} / 5</li>)}</ul></div>}<small>Submitted {challengeDate(claim.submitted_at)}</small></div></div>:participation&&participationWinner?<p className={styles.muted}>You have already won a Participation Champion prize in this course. Keep contributing and supporting the next champion!</p>:phase==='Open'?<button className="lms-button" onClick={()=>setSelected(selected===c.id?'':c.id)}>{selected===c.id?'Cancel':participation?'Submit my weekly reflection':'Submit my achievement'}</button>:<p className={styles.muted}>{phase==='Upcoming'?'Submissions open on the date above.':'Submissions have closed. Results are being reviewed.'}</p>}
 {selected===c.id&&!claim&&<form className={styles.form} onSubmit={e=>submit(e,c)}>{!participation&&<label>When did you achieve it? (Vanuatu time)<input name="achieved" type="datetime-local" required/></label>}<label>{participation?"Your weekly reflection and examples":"Your achievement and proof"}<textarea name="evidence" required minLength={20} maxLength={4000} rows={5} placeholder="What happened, which platform, transaction reference and amount (if applicable). Redact personal and financial details."/></label><label>Private proof or live page link (HTTPS)<input name="url" type="url" pattern="https://.*" maxLength={1000} placeholder="https://…"/></label><p className={styles.muted}>Make your evidence accessible to your trainer. Do not share passwords, account access, or customer personal details.</p><label className={styles.confirm}><input type="checkbox" required/>I confirm this is genuine, meets the challenge rules, and my proof is safe to share with PWD staff.</label><button className="lms-button" disabled={busy}>{busy?'Submitting…':'Send proof for review'}</button></form>}
 </article>;})}</div></section>;
}
