'use client';
import {useEffect,useState} from 'react';
import {challengeRequest} from './Challenges';
import {challengeIdeas,challengeDate,type Challenge,type Claim} from '@/lib/lms/challenges';
import styles from './challenges.module.css';
type CourseOption={id:string;title:string};
const local=(v:string)=>new Date(Date.parse(v)+11*3600000).toISOString().slice(0,16);
export default function ChallengeAdmin({courses}:{courses:CourseOption[]}){const [course,setCourse]=useState(courses[0]?.id||'');return <section><h2>Challenges & prizes</h2><label>Course<select aria-label="Challenge course" value={course} onChange={e=>setCourse(e.target.value)}><option value="">Choose a course</option>{courses.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label>{course&&<Manager key={course} course={course}/>}</section>;}
function Manager({course}:{course:string}){
 const [data,setData]=useState<{challenges:Challenge[];claims:Claim[];admin:boolean}|null>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[edit,setEdit]=useState<Partial<Challenge>|null>(null);
 async function load(){setData(await challengeRequest('?manage=1&course='+course));}
 useEffect(()=>{let current=true;challengeRequest('?manage=1&course='+course).then(d=>{if(current)setData(d);}).catch(e=>{if(current)setError(e.message);});return()=>{current=false;};},[course]);
 async function run(fn:()=>Promise<void>){setBusy(true);setError('');setMessage('');try{await fn();await load();setMessage('Saved.');}catch(e){setError(e instanceof Error?e.message:'Please try again.');}finally{setBusy(false);}}
 function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);void run(async()=>{await challengeRequest('',{action:'save',challenge:{id:edit?.id,course_id:course,title:f.get('title'),description:f.get('description'),proof_instructions:f.get('proof'),prize:f.get('prize'),max_winners:Number(f.get('places')),opens_at:new Date(f.get('opens')+'+11:00').toISOString(),closes_at:new Date(f.get('closes')+'+11:00').toISOString(),published:f.get('published')==='on'}});setEdit(null);});}
 return <div className={styles.root}>{error&&<p role="alert" className={styles.error}>{error}</p>}{message&&<p role="status">{message}</p>}{!data&&!error&&<p>Loading challenges…</p>}
 {data?.admin&&<><p>Start with an idea below. Set the dates and confirm the prize before publishing. Published rules are fixed to keep the competition fair. Rewards are fulfilled manually.</p><div className={styles.ideaGrid}>{challengeIdeas.map((idea,i)=><button key={idea.title} onClick={()=>setEdit({...idea,max_winners:1,published:false})}><span>IDEA {i+1}</span><strong>{idea.title}</strong><small>{idea.prize}</small></button>)}</div><button className="lms-button" onClick={()=>setEdit({max_winners:1,published:false})}>Create a challenge</button></>}
 {edit&&<form key={edit.id||edit.title||'new'} className={styles.form} onSubmit={save}><h3>{edit.id?'Edit draft':'New challenge'}</h3><label>Title<input name="title" required minLength={4} maxLength={120} defaultValue={edit.title}/></label><label>Challenge rules<textarea name="description" required minLength={20} maxLength={3000} rows={4} defaultValue={edit.description}/></label><label>Proof required<textarea name="proof" required minLength={10} maxLength={1500} defaultValue={edit.proof_instructions}/></label><label>Prize (include exact amount and currency for cash)<input name="prize" required minLength={4} maxLength={300} defaultValue={edit.prize}/></label><label>Number of winners<input name="places" type="number" min={1} max={100} required defaultValue={edit.max_winners||1}/></label><label>Opens (Vanuatu time)<input name="opens" type="datetime-local" required defaultValue={edit.opens_at?local(edit.opens_at):''}/></label><label>Closes (Vanuatu time)<input name="closes" type="datetime-local" required defaultValue={edit.closes_at?local(edit.closes_at):''}/></label><label className={styles.confirm}><input name="published" type="checkbox"/>Publish now — I confirm the prize budget and final rules</label><div className={styles.actions}><button disabled={busy} className="lms-button">Save challenge</button><button type="button" onClick={()=>setEdit(null)}>Cancel</button></div></form>}
 {data?.challenges.map(c=><article className={styles.card} key={c.id}><span className={styles.badge}>{c.published?'Published':'Draft'}</span><h3>{c.title}</h3><p>{c.description}</p><p><strong>{c.prize}</strong> · {c.max_winners} prize place(s)</p><p>{challengeDate(c.opens_at)} – {challengeDate(c.closes_at)} · Vanuatu time</p>{!c.published&&data.admin&&<button onClick={()=>setEdit(c)}>Edit / publish draft</button>}<h4>Private submissions</h4><p>Review proof and achievement times before verifying. Entries are ordered by achievement time. Award the earliest verified entry after closing and after reviewing every pending entry. Use the note to explain decisions or record delivery.</p>{!data.claims.some(r=>r.challenge_id===c.id)&&<p>No submissions yet.</p>}{data.claims.filter(r=>r.challenge_id===c.id).map(r=><form key={r.id} className={styles.claim} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(async()=>{await challengeRequest('',{action:'review',id:r.id,status:f.get('status'),note:f.get('note')});});}}><h4>{r.student_name||'Student'} · {r.status}</h4><p>{r.student_email}</p><p>Achieved {challengeDate(r.achieved_at)} · Submitted {challengeDate(r.submitted_at)}</p><p className={styles.evidence}>{r.evidence}</p>{r.evidence_url&&<a href={r.evidence_url} target="_blank" rel="noopener noreferrer">Open submitted proof ↗</a>}<p>{r.review_note}</p>{r.status!=='delivered'&&<><label>Review decision<select name="status" defaultValue={r.status==='winner'?'delivered':'verified'}>{!['winner','delivered'].includes(r.status)&&<><option value="verified">Verify proof</option><option value="rejected">Reject entry</option>{data.admin&&r.status==='verified'&&<option value="winner">Award prize</option>}</>}{data.admin&&r.status==='winner'&&<option value="delivered">Mark prize delivered</option>}</select></label><label>Note visible to student<textarea name="note" required minLength={4} maxLength={1500} defaultValue={r.review_note}/></label><button className="lms-button" disabled={busy||(!data.admin&&r.status==='winner')}>Save decision</button></>}</form>)}</article>)}
 </div>;
}
