export const blpSlug = 'blp-digital-skills-workshop';
export const blpModules = [
  { title: 'Welcome and your business goals', time: '09:00', image: 1, body: 'Choose the business outcome you want to achieve. Write down your starting point and one practical result for today.', task: 'Complete your starting-point check and choose one business goal in your participant workbook.' },
  { title: 'Business identity and readiness', time: '09:15', image: 2, body: 'Prepare accurate business information and identify your next registration step. Keep your business name, contact details and service description consistent.', task: 'Prepare your business facts sheet and note the registration question you will follow up.' },
  { title: 'Get found on Google', time: '09:45', image: 3, body: 'Prepare or improve an eligible Google Business Profile and connect business discovery to your website and customer contact workflow. Verification may continue after the workshop.', task: 'Review your business details, eligibility and photos. Record your next profile improvement or verification step.' },
  { title: 'AI for everyday business', time: '10:30', image: 4, body: 'Use AI to draft useful business copy and practise supported English/Bislama learning. Check the facts, tone and language before sharing anything with customers.', task: 'Draft a short business description, check every claim and ask a peer to review the language.' },
  { title: 'Build your online presence', time: '11:15', image: 5, body: 'Create a website draft in Digi Assist AI using your own business information. Make your offer, contact details and next step clear.', task: 'Build a draft homepage and test whether another participant can understand what you offer and how to contact you.' },
  { title: 'Serve customers online', time: '13:00', image: 5, body: 'Practise a storefront or booking workflow and plan a useful chatbot response. Connect discovery, customer enquiries and service delivery.', task: 'Test one customer journey from enquiry to booking or purchase. Record where human assistance is needed.' },
  { title: 'Professional business documents', time: '14:15', image: 6, body: 'Distinguish invoices from receipts and check a practice transaction. Use fictional information for exercises and check totals and payment status.', task: 'Prepare a practice invoice and receipt, then have a partner check the amounts and payment wording.' },
  { title: 'Protect your digital business', time: '14:45', image: 7, body: 'Choose practical account security actions and rehearse how to respond to a suspicious message. Keep passwords, codes and customer information private.', task: 'Write your account-protection checklist and a response plan for a suspicious message.' },
  { title: 'Review and keep learning', time: '15:30', image: 8, body: 'Review your work and choose a realistic 30-day action plan. Return to your course dashboard for published recordings, workbook activities and instructor questions.', task: 'Choose three next actions, give each a date and identify the support you need.' },
];
